CCDNForum\ForumBundle\Entity\Category:
    type: entity
    table: cc_forum_category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        listOrderPriority:
            type: integer
            column: list_order_priority
        readAuthorisedRoles:
            type: array
            column: read_authorised_roles
            nullable: true
    oneToMany:
        boards:
            targetEntity: CCDNForum\ForumBundle\Entity\Board
            mappedBy: category
            cascade: ["persist", "remove"]
    manyToOne:
        forum:
            targetEntity: CCDNForum\ForumBundle\Entity\Forum
            inversedBy: categories
            nullable: true
            joinColumn:
                name: fk_forum_id
                referencedColumnName: id
                onDelete: SET NULL
