CCDNForum\ForumBundle\Entity\Forum:
    type: entity
    table: cc_forum_forum
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            unique: true
        readAuthorisedRoles:
            type: array
            column: read_authorised_roles
            nullable: true
    oneToMany:
        categories:
            targetEntity: CCDNForum\ForumBundle\Entity\Category
            mappedBy: forum
            cascade: ["persist", "remove"]
