#
# Categories.
#
ccdn_forum_forum_index:
    pattern: /{_locale}/forum
    defaults: { _controller: CCDNForumForumBundle:Category:index, _locale: en }

ccdn_forum_forum_category_index:
    pattern: /{_locale}/forum/index
    defaults: { _controller: CCDNForumForumBundle:Category:index, _locale: en }

ccdn_forum_forum_category_show:
    pattern: /{_locale}/forum/category/{categoryId}
    defaults: { _controller: CCDNForumForumBundle:Category:show, _locale: en }

#
# Boards.
#
ccdn_forum_forum_board_show:
    pattern: /{_locale}/forum/board/{boardId}
    defaults: { _controller: CCDNForumForumBundle:Board:show, _locale: en, page: 1 }
ccdn_forum_forum_board_show_paginated:
    pattern: /{_locale}/forum/board/{boardId}/page/{page}
    defaults: { _controller: CCDNForumForumBundle:Board:show, _locale: en, page: 1 }


#
# Topics.
#
ccdn_forum_forum_topic_show:
    pattern: /{_locale}/forum/topic/{topicId}
    defaults: { _controller: CCDNForumForumBundle:Topic:show, _locale: en, page: 1 }
    
ccdn_forum_forum_topic_show_paginated:
    pattern: /{_locale}/forum/topic/{topicId}/page/{page}
    defaults: { _controller: CCDNForumForumBundle:Topic:show, _locale: en, page: 1 }

# item anchored below is only for use in creating a path, not for a request!
ccdn_forum_forum_topic_show_paginated_anchored:
    pattern: /{_locale}/forum/topic/{topicId}/page/{page}#{postId}

ccdn_forum_forum_topic_create:
    pattern: /{_locale}/forum/topic/create/for/board/{boardId}
    defaults: { _controller: CCDNForumForumBundle:Topic:create, _locale: en, draftId: 0 }

ccdn_forum_forum_topic_create_from_draft:
    pattern: /{_locale}/forum/topic/create/for/board/{boardId}/from/draft/{draftId}
    defaults: { _controller: CCDNForumForumBundle:Topic:create, _locale: en, draftId: 0 }

ccdn_forum_forum_topic_reply:
    pattern: /{_locale}/forum/topic/{topicId}/reply
    defaults: { _controller: CCDNForumForumBundle:Topic:reply, _locale: en, quoteId: 0, draftId: 0 }

ccdn_forum_forum_topic_reply_from_draft:
    pattern: /{_locale}/forum/topic/{topicId}/reply/from/draft/{draftId}
    defaults: { _controller: CCDNForumForumBundle:Topic:reply, _locale: en, quoteId: 0, draftId: 0 }

ccdn_forum_forum_topic_reply_with_quote:
    pattern: /{_locale}/forum/topic/{topicId}/reply/quote/{quoteId}
    defaults: { _controller: CCDNForumForumBundle:Topic:reply, _locale: en, quoteId: 0, draftId: 0 }

#
# Posts.
#
ccdn_forum_forum_post_show:
    pattern: /{_locale}/forum/post/{postId}
    defaults: { _controller: CCDNForumForumBundle:Post:show, _locale: en }

ccdn_forum_forum_post_edit:
    pattern: /{_locale}/forum/post/{postId}/edit
    defaults: { _controller: CCDNForumForumBundle:Post:edit, _locale: en }

ccdn_forum_forum_post_delete:
    pattern: /{_locale}/forum/post/{postId}/delete
    defaults: { _controller: CCDNForumForumBundle:Post:delete, _locale: en }

ccdn_forum_forum_post_delete_confirmed:
    pattern: /{_locale}/forum/post/{postId}/delete/confirm
    defaults: { _controller: CCDNForumForumBundle:Post:deleteConfirmed, _locale: en }

#
# Drafts.
#
ccdn_forum_forum_draft_list:
    pattern: /{_locale}/forum/drafts
    defaults: { _controller: CCDNForumForumBundle:Draft:list, _locale: en, page: 1 }

ccdn_forum_forum_draft_list_paginated:
    pattern: /{_locale}/forum/drafts/page/{page}
    defaults: { _controller: CCDNForumForumBundle:Draft:list, _locale: en, page: 1 }

ccdn_forum_forum_draft_show:
    pattern: /{_locale}/forum/draft/{draftId}/show
    defaults: { _controller: CCDNForumForumBundle:Draft:show, _locale: en }

ccdn_forum_forum_draft_delete:
    pattern: /{_locale}/forum/draft/{draftId}/delete
    defaults: { _controller: CCDNForumForumBundle:Draft:delete, _locale: en }

ccdn_forum_forum_draft_publish:
    pattern: /{_locale}/forum/draft/{draftId}/publish
    defaults: { _controller: CCDNForumForumBundle:Draft:publish, _locale: en }

#
# Subscriptions.
#
ccdn_forum_forum_subscription_list:
    pattern: /{_locale}/forum/subscriptions
    defaults: { _controller: CCDNForumForumBundle:Subscription:show, _locale: en, page: 1 }

ccdn_forum_forum_subscription_list_paginated:
    pattern: /{_locale}/forum/subscriptions/page/{page}
    defaults: { _controller: CCDNForumForumBundle:Subscription:show, _locale: en, page: 1 }

ccdn_forum_forum_subscription_subscribe:
    pattern: /{_locale}/forum/subscriptions/topic/{topicId}/subscribe
    defaults: { _controller: CCDNForumForumBundle:Subscription:subscribe, _locale: en }

ccdn_forum_forum_subscription_unsubscribe:
    pattern: /{_locale}/forum/subscriptions/topic/{topicId}/unsubscribe
    defaults: { _controller: CCDNForumForumBundle:Subscription:unsubscribe, _locale: en }












ccdn_forum_admin_topic_close:
    pattern: /{_locale}/forum/topic/{topicId}/close
    defaults: { _controller: CCDNForumForumBundle:TopicModerator:close, _locale: en }

ccdn_forum_admin_topic_reopen:
    pattern: /{_locale}/forum/topic/{topicId}/reopen
    defaults: { _controller: CCDNForumForumBundle:TopicModerator:reopen, _locale: en }

ccdn_forum_admin_topic_sticky:
    pattern: /{_locale}/forum/topic/{topicId}/sticky
    defaults: { _controller: CCDNForumForumBundle:TopicModerator:sticky, _locale: en }

ccdn_forum_admin_topic_unsticky:
    pattern: /{_locale}/forum/topic/{topicId}/unsticky
    defaults: { _controller: CCDNForumForumBundle:TopicModerator:unsticky, _locale: en }

ccdn_forum_admin_topic_delete:
    pattern: /{_locale}/forum/topic/{topicId}/delete
    defaults: { _controller: CCDNForumForumBundle:TopicModerator:delete, _locale: en }

ccdn_forum_admin_topic_delete_confirmed:
    pattern: /{_locale}/forum/topic/{topicId}/delete/confirm
    defaults: { _controller: CCDNForumForumBundle:TopicModerator:deleteConfirmed, _locale: en }

ccdn_forum_admin_topic_restore:
    pattern: /{_locale}/forum/topic/{topicId}/restore
    defaults: { _controller: CCDNForumForumBundle:TopicModerator:restore, _locale: en }

ccdn_forum_forum_topic_change_board:
    pattern: /{_locale}/forum/topic/{topicId}/change/board
    defaults: { _controller: CCDNForumForumBundle:TopicModerator:move, _locale: en }






ccdn_forum_admin_post_lock:
    pattern: /{_locale}/forum/post/{postId}/lock
    defaults: { _controller: CCDNForumForumBundle:PostModerator:lock, _locale: en }

ccdn_forum_admin_post_unlock:
    pattern: /{_locale}/forum/post/{postId}/unlock
    defaults: { _controller: CCDNForumForumBundle:PostModerator:unlock, _locale: en }

ccdn_forum_admin_post_restore:
    pattern: /{_locale}/forum/post/{postId}/restore
    defaults: { _controller: CCDNForumForumBundle:PostModerator:restore, _locale: en }