parameters:

    # Service Parameters defined in app/config.

services:

    #
    # Managers.
    #

    ccdn_forum_forum.manager.forum:
        class: %ccdn_forum_forum.manager.forum.class%
        arguments:
            - @ccdn_forum_forum.gateway.forum

    ccdn_forum_forum.manager.category:
        class: %ccdn_forum_forum.manager.category.class%
        arguments:
            - @ccdn_forum_forum.gateway.category

    ccdn_forum_forum.manager.board:
        class: %ccdn_forum_forum.manager.board.class%
        arguments:
            - @ccdn_forum_forum.gateway.board

    ccdn_forum_forum.manager.topic:
        class: %ccdn_forum_forum.manager.topic.class%
        arguments:
            - @ccdn_forum_forum.gateway.topic
            - @ccdn_forum_forum.component.helper.post_lock

    ccdn_forum_forum.manager.post:
        class: %ccdn_forum_forum.manager.post.class%
        arguments:
            - @ccdn_forum_forum.gateway.post
            - @ccdn_forum_forum.component.helper.post_lock

    ccdn_forum_forum.manager.registry:
        class: %ccdn_forum_forum.manager.registry.class%
        arguments:
            - @ccdn_forum_forum.gateway.registry

    ccdn_forum_forum.manager.subscription:
        class: %ccdn_forum_forum.manager.subscription.class%
        arguments:
            - @ccdn_forum_forum.gateway.subscription
