
#
# CRUD
#
ccdn_forum_user_topic_show:
    pattern: /{topicId}
    defaults: { _controller: CCDNForumForumBundle:UserTopic:show, _locale: en, forumName: default }

ccdn_forum_user_topic_create:
    pattern: /create/for-board/{boardId}
    defaults: { _controller: CCDNForumForumBundle:UserTopic:create, _locale: en, forumName: default }

ccdn_forum_user_topic_create_process:
    pattern: /create/for-board/{boardId}/process
    defaults: { _controller: CCDNForumForumBundle:UserTopic:createProcess, _locale: en, forumName: default }

ccdn_forum_user_topic_reply:
    pattern: /{topicId}/reply
    defaults: { _controller: CCDNForumForumBundle:UserTopic:reply, _locale: en, forumName: default }

ccdn_forum_user_topic_reply_process:
    pattern: /{topicId}/reply/process
    defaults: { _controller: CCDNForumForumBundle:UserTopic:replyProcess, _locale: en, forumName: default }
