#
# CRUD
#
ccdn_forum_user_post_show:
    pattern: /{postId}
    defaults: { _controller: CCDNForumForumBundle:UserPost:show, _locale: en, forumName: default }

ccdn_forum_user_post_edit:
    pattern: /{postId}/edit
    defaults: { _controller: CCDNForumForumBundle:UserPost:edit, _locale: en, forumName: default }

ccdn_forum_user_post_edit_process:
    pattern: /{postId}/edit/process
    defaults: { _controller: CCDNForumForumBundle:UserPost:editProcess, _locale: en, forumName: default }

ccdn_forum_user_post_delete:
    pattern: /{postId}/delete
    defaults: { _controller: CCDNForumForumBundle:UserPost:delete, _locale: en, forumName: default }

ccdn_forum_user_post_delete_process:
    pattern: /{postId}/delete/process
    defaults: { _controller: CCDNForumForumBundle:UserPost:deleteProcess, _locale: en, forumName: default }
